### ISSUE TITLE
Great template. But how do I handle url query parameters?

### ISSUE THREAD

**Issue by OElesin** [theiterators/akka-http-microservice#10]
My current REST APIs have something like [api-url]?start=[parameter]&end=[parameter]. 
How do I handle this with the template. Relatively new to Akka

Thanks

**Comment by luksow** [comment]
@OElesin thanks for getting in touch! For URL params there's of course a directive `parameters`: http://spray.io/documentation/1.2.3/spray-routing/parameter-directives/parameters/#parameters So for ex. in your case it'll be 
```
parameters('start.as[Int], 'end.as[Int]) { (start, end) =>
...
}
```

Hope that helps. If so, please close the issue.

**Comment by OElesin** [comment]
Alright. Thanks

**Comment by OElesin** [comment]
Yet another question. What if I want to handle HTTP form-post or x-www-form-urlencodec?

**Comment by luksow** [comment]
In fact, it's very very similar: http://spray.io/documentation/1.2.3/spray-routing/form-field-directives/formFields/ I generally recommend skimming all the directive listing in the docs.
