### ISSUE TITLE
Update to Akka Streams 1.0

### ISSUE THREAD

**Issue by ktoso** [theiterators/akka-http-microservice#11]
Please update to Akka Streams 1.0.
This template is rather high up in google search results, it would be awesome if it would be up to date. :smile: 

Thanks!

**Comment by jglodek** [comment]
:+1:

**Comment by luksow** [comment]
@ktoso
Thanks for getting in touch. What do you specifically have in mind mentioning update to Akka Streams 1.0? There's this commit: https://github.com/theiterators/akka-http-microservice/commit/f15b004ac285959674b9896e2424d2acfdfcecb5 but probably you would like to see some code changes, right?

**Comment by ktoso** [comment]
Oh, seems indeed you've upgraded already.
I opened this ticket after some feedback from the community "that template is cool but outdated" someone said (mentioning that it used `ActorFlowMaterializer` instead of `ActorMaterializer`, but that's not the case AFAICS).

Closing this as invalid then, sorry for the noise!

**Comment by luksow** [comment]
Ok, thanks for caring anyway! :+1:

**Comment by ktoso** [comment]
Something is wrong anyway - I don't see this project when using `activator ui`. 
Do you have the github hook setup properly?

**Comment by luksow** [comment]
Ok fixed - it was a silly problem. We've recently changed location of authorLogo (http vs https) and publishing constantly failed. Good catch, thanks!

**Comment by ktoso** [comment]
Awesome, glad we found/fixed it :)
