### ISSUE TITLE
Proxy usage example?

### ISSUE THREAD

**Issue by nanothermite** [theiterators/akka-http-microservice#13]
Hi,
Any example incorporating the proxy settings such as this:

https://gist.github.com/rklaehn/3aa3215046df2c0a7795

Thanks,
Henry

**Comment by luksow** [comment]
Could you provide a little more context? What you're trying to achieve? Where are you stuck?

**Comment by nanothermite** [comment]
Thanks for the response. 

The simple issue is the inability to have the activator environment
inherit the shell environment in which I am able to use the proxy to
bypass the firewall and to access the telize.com REST service. The
application.conf had the akka.http block added: 

akka { 

 loglevel = DEBUG 

} 

http { 

 interface = "0.0.0.0" 

 port = 9000 

} 

services { 

 telizeHost = "www.telize.com" 

 telizePort = 80 

} 

akka.http { 

 client { 

 proxy { 

 http = default 

 } 

 } 

} 

but this reliance on the default (I have even specified the proxy host
and port as well) still yields an exception: 

[DEBUG] [10/14/2015 10:04:02.651]
[default-akka.actor.default-dispatcher-2]
[akka://default/system/IO-TCP/selectors/$a/2] Could not establish
connection to [www.telize.com:80] due to
java.nio.channels.UnresolvedAddressException 

[ERROR] [10/14/2015 10:04:02.674]
[default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Error
during processing of request
HttpRequest(HttpMethod(GET),http://localhost:9000/ip/8.8.8.8,List(Host:
localhost:9000, Connection: keep-alive, Accept-Encoding: gzip, deflate,
Accept: */*, User-Agent:
HTTPie/0.9.2),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
(akka.stream.StreamTcpException) 

when attempting to return a response: 

% http --print b --pretty format GET "http://localhost:9000/ip/8.8.8.8" 

There was an internal server error. 

Presumably there is an easy solution? 

Thanks, 

Henry 

On 2015-10-14 08:18, Łukasz Sowa wrote: 

> Could you provide a little more context? What you're trying to achieve? Where are you stuck? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/theiterators/akka-http-microservice/issues/13#issuecomment-148046712

**Comment by luksow** [comment]
Hmm, I don't know answer for activator env but perhaps you can change adresses in the code or run service outside of activator?

**Comment by Madder** [comment]
Hi, 

Please note that I have a similar issue. 
The example works fine from a windows machine at home, but fails at work (behind proxy) with the same setup.
I've tried to add this in application.conf as explained in akka-http docs:
akka.http {
     client {
		proxy {	 
		      http {
		         host = "proxy"
		         port = "3128"
		         non-proxy-hosts = ["*.murex.com","localhost","127.0.0.1","0.0.0.0", "murex.com"]
		       }
		 
		      # Proxy settings for HTTPS requests (currently unsupported)
		      https {
		         host = "proxy"
		         port = "3128"
		         non-proxy-hosts = ["*.murex.com","localhost","127.0.0.1","0.0.0.0", "murex.com"]
		       }
		      
		      
		}
	}
}

I've also added the proxy settings in sbtconfig.txt (and it seems to work as sbt is able to download arifacts..). My Windows proxy environment variables (http_proxy, https_proxy) are also set.

Did I miss anything?

Many thanks,
Omar

**Comment by Madder** [comment]
Actually using an HTTP proxy server is still not supported in Akka-http client  #16853.
Akka-http client is still incomplete and proxy support is on the TO DO list according to #16856.

**Comment by luksow** [comment]
Thanks @Madder for letting us know. As far as I understood from links you provided there's not much we can do about it now :-(

**Comment by jninja** [comment]
Is HTTP proxy server still not supported in Akka-http client? That's a basic feature!

**Comment by luksow** [comment]
@jninja please check out links given by @Madder. tldr; not yet.
