### ISSUE TITLE
No more free public api from telize.com

### ISSUE THREAD

**Issue by Mironor** [theiterators/akka-http-microservice#14]
From http://www.telize.com:

>  The public API will permanently shut down on November 15th, 2015. More information can be found here [http://www.cambus.net/adventures-in-running-a-free-public-api/].
>  To continue using Telize after this date, please spin up your own instance or subscribe to a paid plan.

**Comment by luksow** [comment]
Oh, that's sad news. Thanks for letting me know though. I'll work something out.

**Comment by luksow** [comment]
@Mironor fixed in https://github.com/theiterators/akka-http-microservice/commit/fa4eb0041c674cb0a3d88da1b5f11e5428da9cdc Again, thanks for noticing us about it!
