### ISSUE TITLE
Any service management solution?

### ISSUE THREAD

**Issue by xushuxun** [theiterators/akka-http-microservice#143]
Hi, how to manage a akka-http-microservice?

For example, configuration, service registry & discovery, log, metrics, tracing, load balancing, rate limit...

**Comment by luksow** [comment]
Hi, great question. These topics are beyond the scope of this project but I can share my usual approach:
- configuration via envs (native support in https://github.com/lightbend/config), orchestrated by docker,
- metrics fed into https://www.datadoghq.com/ (open source alternatives exist) via https://kamon.io/
- traces fed into https://www.datadoghq.com/ via https://kamon.io/
- logs, as handled by logback, fed into https://www.datadoghq.com/
- load balancing, rate limiting - whatever works for you, could be nginx or kong or whatever you like
- service registry & discovery - whatever works nicely with JVM is fine

HTH. I can elaborate on any of these, if you want.

**Comment by xushuxun** [comment]
Thank you for your detailed reply！The information is enough for me to investigate and experiment
