### ISSUE TITLE
unable to start the project after getting it with activator ui

### ISSUE THREAD

**Issue by stondo** [theiterators/akka-http-microservice#16]
HI there,

as soon as I try to build the project I'm getting this:

    stondo@H97-D3H:~/dev/scala/akka-http-microservice-quickstart$ sbt
    [info] Loading project definition from /home/stondo/dev/scala/akka-http-microservice-quickstart/project
    [error] [/home/stondo/dev/scala/akka-http-microservice-quickstart/build.sbt]:64: ';' expected but 'true' found.
    Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

Anyone know what might be wrong? Installed Scala 2.11.7 with sdkman.io and using Ubuntun 14.04. Sbt version is 0.13.9
Thanks in advance for your help

**Comment by luksow** [comment]
Hi,
Sounds like a problem with activator itself or another project - `akka-http-microservice` does not have 64 lines in `build.sbt`. Have you tried running vanilla version straight from command line?

**Comment by stondo** [comment]
Yes, you are right. Just cloning your repo and running sbt works fine. build.sbt is smaller.  Don't know what went wrong with Activator UI though. I used the minimal version, but as far as I know, that shouldn't be a problem.
Anyway, thanks for your help!
