### ISSUE TITLE
Current status of AKKA HTTP

### ISSUE THREAD

**Issue by alexander-myltsev** [theiterators/akka-http-microservice#18]
Please, explain current status of dependencies that ends in `-experimental`. Are they production-ready?

**Comment by luksow** [comment]
Hi @alexander-myltsev, thanks for getting in touch. The best explaination of experimental tag is one on Akka's webpage: http://doc.akka.io/docs/akka/2.4.2/experimental/index.html Also please note that from 2.4.2 release akka-http-core is no longer marked as experimental (https://groups.google.com/forum/#!topic/akka-user/c473YbKpjvE), so it's only akka-http-experimental that's left, from important bits at least.

As for my *personal opinion* Akka HTTP is ready for production. If you need careful examination of your case, contact me via mail.

Let me know if that helps.

**Comment by alexander-myltsev** [comment]
Sounds promising. I will give it a shot. Thanks for keeping me updated!
