### ISSUE TITLE
ERROR running akka-http-microservice Activator template 

### ISSUE THREAD

**Issue by DagnyTagg2013** [theiterators/akka-http-microservice#21]
Error running akka-http-microservice Activator template 
Unable to run example template: akka-http-microservice from the Activator

Project builds, but on running, unable to access URL, http://localhost:9000/ip/8.8.8.8 getting 'Internal Server Error'

Error on running service: [ERROR] [04/21/2016 12:06:35.506] [default-akka.actor.default-dispatcher-10] [akka://default/user/StreamSupervisor-0/flow-2-0-unknown-operation] Error in stage [One2OneBidi]: Inner stream finished before inputs completed. Outputs might have been truncated. (akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$)

This is just with code taken directly from downloaded template *.zip file.

Running on Mac OSx, El Capitan. Running Scala v2.10.3.  Activator v1.3.9

**Comment by luksow** [comment]
Hi, thanks for reporting. It seems that geo ip API we used is down. I've just changed to another one, let me know if that fixes your problem.
