### ISSUE TITLE
Tutorial still references freegeoip.net

### ISSUE THREAD

**Issue by robmoore** [theiterators/akka-http-microservice#22]
Not a big deal but confused me until I looked at the commit log.

**Comment by jglodek** [comment]
Thanks for the notice!

**Comment by luksow** [comment]
@robmoore mind issuing a PR against that?

**Comment by robmoore** [comment]
Sure thing!

**Comment by jglodek** [comment]
@robmoore @luksow i fixed this i guess, but please review the changes.

**Comment by robmoore** [comment]
I will review. 

Perhaps this should go somewhere else but I wanted to let you know that there's a confusing aspect of how things are working today. When I go to the Lightbend page (http://www.lightbend.com/activator/template/akka-http-microservice) it says I can type akka-http-microservice in the Activator UI to find the project. However, doing so takes me to another project (https://github.com/owainlewis/activator-akka-http). Not sure what's up there but thought you'd like to know.

**Comment by luksow** [comment]
@robmoore thank's for letting me know. That's strange, I'll try to reach out to Activator people about it.
