### ISSUE TITLE
hrefs in tutorial reference non-existent ids/names

### ISSUE THREAD

**Issue by robmoore** [theiterators/akka-http-microservice#23]
As an example:

`<li>learn <a href="#tutorial/1" class="shortcut">what a microservice is</a>,</li>`

but there's no anchor defined 

`<div>
      <h2>What is a microservice?</h2>
      <p>`

An `id` attribute or an `<a name>...</a>` element needs to be defined for these to work.

**Comment by robmoore** [comment]
Maybe this usage is OK for Activator-consumed html. I'm using a regular browser to review the docs so the anchors don't work for me.

**Comment by luksow** [comment]
Yeah, that's how it works with activator UI. I'm wondering if it's possible to make it work with both views...

**Comment by robmoore** [comment]
I would think that Activator would ignore the `id` attribute.
