### ISSUE TITLE
JVM Heap Memory Leak Issue

### ISSUE THREAD

**Issue by ramkumardnagarajan** [theiterators/akka-http-microservice#28]
I have used this template to create a search rest API for my project. I have deployed my micro service in AWS EBS with Docker setup. I have allocate 512 MB Memory for docker. When I request my rest API from some tool(post man/j meter) the heap memory and CPU utilization was increased, after the stop the request CPU utilization decreased but heap memory not decreased instead when the next set ot request comes heap memory increased again. 
There is any was to fix this issue by clearing the unused objects from the Scala code. I need to close(shutdown) the actor object manually or it will be deleted by the JVM's GC.

**Comment by jglodek** [comment]
JVM should take care of it, checkout some paper on how to configure JVM Garbage Collector, shouldnt have much to do with this partticular code. Also docker has new JVM garbage collector options, since last few weeks I think.

**Comment by ramkumardnagarajan** [comment]
@jglodek  I have tested the heap memory of the service in local using visualVM. In that heap memory of my service increase while in the idle time(i.e no request from user).There is any way to handle this by code.
I had configured the JVM garbage collection (-XX:+UseParallelGC and -XX:+UseConcMarkSweepGC), but the result was same.

**Comment by Maiakov** [comment]
@ramkumardnagarajan Did you solve your problem ? I have exactly same issue. After few days of researching where I found that all objects which were send in response remains in heap... The only way to fix that - call gc manually but this is not the solution (

**Comment by reddysekharnanchari** [comment]
@Maiakov Same problem I have faced, for that I have used below java options in docker file my problem solved.
`ENV JAVA_OPTS="-XX:+UseNUMA -XX:+UseCondCardMark -XX:-UseBiasedLocking -Xms128M -Xmx400M -Xss1M -XX:+UseParallelGC -XX:MaxGCPauseMillis=100 -XX:GCTimeRatio=19"`
