### ISSUE TITLE
Marshalling object

### ISSUE THREAD

**Issue by kenadet** [theiterators/akka-http-microservice#29]
Can I do this for a case object?

trait Protocols extends DefaultJsonProtocol {
   implicit val ipInfoFormat = jsonFormat5(IpInfo.apply)
   implicit val ipPairSummaryRequestFormat = jsonFormat2(IpPairSummaryRequest.apply)
  implicit val ipPairSummaryFormat = jsonFormat3(IpPairSummary.apply)
}

**Comment by luksow** [comment]
Hi, no, not really, but have a look at https://github.com/lloydmeta/enumeratum - there's support for some JSON formats there, not `spray-json` unfortunately but it's pretty easy to add.
