### ISSUE TITLE
Errors should be JSONified (and not assume Accept: text/plain header)

### ISSUE THREAD

**Issue by jaceklaskowski** [theiterators/akka-http-microservice#3]
Errors should really be JSON responses with appropriate `Content-Types` headers.

The following sends a JSON request using `Accept` and `Content-Types` set to `application/json`:

```
➜  ~  http -j http://localhost:9000/ip/8.8
HTTP/1.1 406 Not Acceptable
Content-Length: 78
Content-Type: text/plain; charset=UTF-8
Date: Sun, 01 Feb 2015 10:43:21 GMT
Server: akka-http/2.3.9

Resource representation is only available with these Content-Types:
text/plain
```

When I explicitly say I'm accepting `test/plain` it's fine:

```
➜  ~  http -j http://localhost:9000/ip/8.8 Accept:text/plain,application/json
HTTP/1.1 400 Bad Request
Content-Length: 24
Content-Type: text/plain; charset=UTF-8
Date: Sun, 01 Feb 2015 10:44:13 GMT
Server: akka-http/2.3.9

8.8: incorrect IP format
```

The same happens with the following when it's implicitly assumed POST in JSON `Accept` and `Content-Types` headers:

```
➜  ~  http http://localhost:9000/ip/8.8.8.8 ip1=8.8.8.8 ip2=8.8
HTTP/1.1 406 Not Acceptable
Content-Length: 78
Content-Type: text/plain; charset=UTF-8
Date: Sun, 01 Feb 2015 10:46:06 GMT
Server: akka-http/2.3.9

Resource representation is only available with these Content-Types:
text/plain
```

With explicitly accepting non-JSON responses using `Accept:text/plain` it works:

```
➜  ~  http http://localhost:9000/ip/8.8.8.8 Accept:text/plain,application/json ip1=8.8.8.8 ip2=8.8
HTTP/1.1 400 Bad Request
Content-Length: 24
Content-Type: text/plain; charset=UTF-8
Date: Sun, 01 Feb 2015 10:45:07 GMT
Server: akka-http/2.3.9

8.8: incorrect IP format
```

**Comment by luksow** [comment]
As errors are presented in plain text, this behaviour is expected. You could easily JSONify all errors by:
* JSONifying by hand where you handle it manually (like `case Left(errorMessage) => ToResponseMarshallable(BadRequest -> errorMessage)`),
* overriding default exception handler (http://doc.akka.io/api/akka-stream-and-http-experimental/current/index.html#akka.http.server.ExceptionHandler)
* overriding default rejection handler (http://doc.akka.io/api/akka-stream-and-http-experimental/current/index.html#akka.http.server.RejectionHandler)
It's easy to do but goes beyond simple example like this one - not every project needs well-formed JSON APIs.

**Comment by quelgar** [comment]
The behaviour is correct, but it can be annoying. I would want to do simply `complete(StatusCodes.NotFound)`, but as the clients I'm dealing with often only accept `application/json`, they get a quite unhelpful `406`.

I found the simplest way to deal with it was something like:

```scala
  implicit val m: ToResponseMarshaller[StatusCode] = Marshaller.oneOf(
    Marshaller.fromStatusCode,
    Marshaller.withFixedContentType(ContentTypes.`application/json`) { s =>
      HttpResponse(s, entity = HttpEntity(ContentTypes.`application/json`,
        s"{\"message\":\"${s.defaultMessage}\"}"))
    }
  )
```

I don't think it makes sense to build this in to the default marshaller.

**Comment by luksow** [comment]
@quelgar That's a very interesting approach, thanks for sharing!
