### ISSUE TITLE
Consider host-level api for sending requests

### ISSUE THREAD

**Issue by evbo** [theiterators/akka-http-microservice#32]
Please note there's a couple great discussions discouraging the use of `Source.single` when sending a request list is done in the [AkkaHttpMicroservice](https://github.com/theiterators/akka-http-microservice/blob/master/src/main/scala/AkkaHttpMicroservice.scala#L64):

https://doc.akka.io/docs/akka-http/current/client-side/host-level.html?language=scala#examples

https://stackoverflow.com/questions/44241920/akka-http-host-level-client-side-api-source-queue-pattern

> At this place we previously showed an example that used the Source.single(request).via(pool).runWith(Sink.head). In fact, this is an anti-pattern that doesn’t perform well. Please either supply requests using a queue or in a streamed fashion as shown below.

You might want to consider just adding a comment in your code referencing this so as to not advertise this *anti-pattern* as the Akka docs describe it (if not refactor the code a bit to make use of host-level api)

**Comment by luksow** [comment]
Hi! Thanks for pointing that out. I of course agree. However, I left it as it was to keep it simple. Very often, a single request is all that people need. I added a comment pointing to this issue: https://github.com/theiterators/akka-http-microservice/commit/e45248f35b61b030f61d63b3d62d58236e6d8b12
